/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.hcxprotocol.lib;

import org.junit.jupiter.api.Test;

import static org.junit.Assert.*;

class LibraryTest {
    @Test
     void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
