name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
  push :
    branches :
      - local-2
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name : settings.xml file
        uses: s4u/maven-settings-action@v2.3.0
        with:
          servers: |
            [{
            "id": "ossrh",
            "username": "${{ secrets.OSSRH_USERNAME }}",
            "password": "${{ secrets.OSSRH_TOKEN }}",
            "gpg-passphrase": "${{ secrets.GPG_PASSPHRASE }}"
            "gpg-private-key": "${{ secrets.OSSRH_GPG_SECRET_KEY }}"
            
            }]
            
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}

      - name: Publish to the Maven Central Repository
        run: |
            cd hcx-integrator-sdk/
            mvn clean deploy 
       
            
            
    
