name: Maven Package

on:
  push:
    branches: local-2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name : Checkout repository
        uses : actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v1
        with:
         java-version: 11
         server-id: ossrh
         server-username: ${{ secrets.OSSRH_USERNAME }}
         server-password: ${{ secrets.OSSRH_TOKEN }}
         gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
         gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name : Print Credentials for the verification
        run: |
          echo $server-username
          echo $server-password
          echo $gpg-private-key
          echo $gpg-passphrase
      - name : Build artifact
        run: mvn clean package
      - name : Build with Maven
        run: mvn clean -B package -s .maven/settings.xml
      - name : deploy to maven central repository
        run: mvn clean -B package deploy -s .maven/settings.xml
     
        env:
           GITHUB_TOKEN : ${{ secrets.TOKEN }}




