on:
 push :
    branches :
      - local-2
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          server-id: ossrh
          server-username: ${{ env.OSSRH_USERNAME }}
          server-password: ${{ env.OSSRH_TOKEN }}
          gpg-private-key: ${{ env.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          
      - name : list of keys
        run : gpg --list-keys

      - name: Install gpg secret key
        run: |
              cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import
              gpg --list-secret-keys --keyid-format LONG
              
      - name: Publish to the Maven Central Repository
        run: |
          cd hcx-integrator-sdk/
          mvn clean deploy  -s ./.maven/settings.xml
      
