name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
  push :
    branches :
      - local-2
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name : settings.xml file
        uses: s4u/maven-settings-action@v2.3.0
        with:
         servers: |
          [{
            "id": "github",
             "username": "$GITHUB_ACTOR",
             "password": "$GITHUB_TOKEN",
              "gpg-passphrase": "${{ secrets.GPG_PASSPHRASE }}"
           }]
      - name : path
        run : pwd
      - name : list dir
        run : |
              cd /home/runner/.m2
              cat settings.xml
        
        
      - name: Publish to the Maven Central Repository
        run: |
          cd hcx-integrator-sdk/
          run: mvn clean deploy -s /home/runner/.m2/settings.xml
        env :
             GITHUB_ACTOR : ${{ env.GIT_USERNAME }}
             GITHUB_TOKEN : ${{ env.GIT_PASSWORD }}
       
