name: Maven Package

on:
  push:
    branches: local-2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name : Checkout repository
        uses : actions/checkout@v2
      
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
             gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
             passphrase: ${{ secrets.GPG_PASSPHRASE }}
             git_user_signingkey: true
             git_commit_gpgsign: true
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v1
        with:
         java-version: 11
         server-id: ossrh
         server-username: ${{ secrets.OSSRH_USERNAME }}
         server-password: ${{ secrets.OSSRH_TOKEN }}
         gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
         gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
     
      - name : Build with Maven
        run: mvn clean install -DskipTests -s ../.maven/settings.xml
      - name : deploy to maven central repository
        run: mvn clean deploy  -DskipTests -s ../.maven/settings.xml
     
        env:
           GITHUB_TOKEN : ${{ secrets.TOKEN }}




