name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
  push :
    branches :
      - local-2
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: s4u/maven-settings-action@v2.3.0
      - with:
          servers: |
            [{
            "server-id": "ossrh",
            "server-username": "${{ secrets.OSSRH_USERNAME }}",
            "server-password": "${{ secrets.OSSRH_TOKEN }}",
            "gpg-passphrase": "${{ secrets.GPG_PASSPHRASE }}"
            
            }]

      - name: Publish to the Maven Central Repository
      - run: |
          cd hcx-integrator-sdk/
          mvn clean deploy 
