on:
  release:
    types: [created]
  push :
    branches :
      - local-2
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Install gpg secret key
        run: |
              cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
              gpg --list-secret-keys --keyid-format LONG
              
      - name: Publish to the Maven Central Repository
        run: |
          cd hcx-integrator-sdk/
           mvn \
              --no-transfer-progress \
              --batch-mode \
              -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} \
              clean deploy -s ./.maven/settings.xml
      
