name: Maven Package

on:
  push:
    branches: local-2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name : Checkout repository
        uses : actions/checkout@v2
      - name : Build with Maven
        run: mvn clean -B package -s .maven/settings.xml
      - name : deploy to maven central repository
        run: mvn clean -B package deploy -s .maven/settings.xml
      - name: Configure GPG Key
        run: |
         echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          GITHUB_TOKEN : ${{ secrets.TOKEN }}



