name: release and push to central
on:
  push:
    branches:
      - local-2
        
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username:  ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase:  ${{ secrets.GPG_PASSPHRASE }}
   
      - name : listing gpg keys
        run : gpg --list-keys
      
      - name : cat settings.xml
        run : cat ./.maven/settings.xml
      - name : maven clean install
        run : mvn clean install -s ./.maven/settings.xml
   
      - name: Publish to the Maven Central Repository
        run:  mvn clean deploy -s ./.maven/settings.xml
        env:
            GITHUB_TOKEN : ${{ secrets.TOKEN }}
           
        
