name: release and push to central
on:
  push:
    branches:
      - local-2
jobs:
  publish:
    runs-on: ubuntu-latest
    steps :
     - name: maven-settings-xml-action
       uses: whelk-io/maven-settings-xml-action@v20
       with:
          servers: >
           [ 
            {
              "id": "ossrh",
              "username": "${{ secrets.OSSRH_USERNAME }}",
              "password": "${{ secrets.OSSRH_TOKEN }}",
              "configuration": {
                "httpConfiguration": {
                  "all": {
                    "usePreemptive": "true"
                  }
                }
              }
            }
          ]
          profiles: >
           [
            {
            "id":"ossrh",
            "properties" :{
               "gpg.executable":"gpg",
               "gpg.passphrase":"${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}"
            }

            }
          ]
     - name : Publish to the Maven Central Repository
       run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            deploy





